update

diff --git a/.github/workflows/terraform-pipeline-pr.yml b/.github/workflows/terraform-pipeline-pr.yml
--- a/.github/workflows/terraform-pipeline-pr.yml
+++ b/.github/workflows/terraform-pipeline-pr.yml
@@ -47,57 +47,124 @@ jobs:
           level: info  # change to info for more information
           tflint_rulesets: "aws"
           working_directory: terraform
-      # - name: Terraform Plan
-      #   id: plan
-      #   if: github.event_name == 'pull_request'
-      #   run: terraform plan -no-color -out plan
-      #   continue-on-error: true
-      # - name: Terraform show plan output
-      #   uses: mathiasvr/command-output@v1
-      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
-      #   id: plan_output
-      #   with:
-      #     run: terraform show -no-color plan
-      # - name: Comment on PR on success
-      #   uses: actions/github-script@v6
-      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
-      #   env:
-      #     PLAN: "${{ steps.plan_output.outputs.stdout }}"
-      #   with:
-      #     script: |
-      #       const output = `##### Plan:
-      #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-      #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-      #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-      #       <details><summary>Show Plan</summary>
-      #       \`\`\`terraform\n
-      #       ${process.env.PLAN}
-      #       \n\`\`\`
-      #       </details>
-      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: output
-      #       })
-      # - name: Comment on PR on error
-      #   uses: actions/github-script@v6
-      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
-      #   with:
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     script: |
-      #       const output = `##### Plan:
-      #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-      #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-      #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: output
-      #       })
-      # - name: Terraform Plan Status
-      #   if: steps.plan.outcome == 'failure'
-      #   run: exit 1 
+      - name: Terraform fmt
+        id: fmt
+        run: terraform -chdir=terraform fmt -check
+        continue-on-error: true
+
+      - name: Terraform Plan
+        id: plan
+        run: terraform -chdir=terraform plan -no-color
+        continue-on-error: true
+
+      - uses: actions/github-script@v6
+        if: github.event_name == 'pull_request'
+        env:
+          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            // 1. Retrieve existing bot comments for the PR
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const botComment = comments.find(comment => {
+              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
+            })
+
+            // 2. Prepare format of the comment
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+            <details><summary>Validation Output</summary>
+
+            \`\`\`\n
+            ${{ steps.validate.outputs.stdout }}
+            \`\`\`
+
+            </details>
+
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
+            <details><summary>Show Plan</summary>
+
+            \`\`\`\n
+            ${process.env.PLAN}
+            \`\`\`
+
+            </details>
+
+            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+
+            // 3. If we have a comment, update it, otherwise create a new one
+            if (botComment) {
+              github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: botComment.id,
+                body: output
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: output
+              })
+            }
+          # - name: Terraform Plan
+          #   id: plan
+          #   if: github.event_name == 'pull_request'
+          #   run: terraform plan -no-color -out plan
+          #   continue-on-error: true
+          # - name: Terraform show plan output
+          #   uses: mathiasvr/command-output@v1
+          #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
+          #   id: plan_output
+          #   with:
+          #     run: terraform show -no-color plan
+          # - name: Comment on PR on success
+          #   uses: actions/github-script@v6
+          #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
+          #   env:
+          #     PLAN: "${{ steps.plan_output.outputs.stdout }}"
+          #   with:
+          #     script: |
+          #       const output = `##### Plan:
+          #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+          #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+          #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+          #       <details><summary>Show Plan</summary>
+          #       \`\`\`terraform\n
+          #       ${process.env.PLAN}
+          #       \n\`\`\`
+          #       </details>
+          #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+          #       github.rest.issues.createComment({
+          #         issue_number: context.issue.number,
+          #         owner: context.repo.owner,
+          #         repo: context.repo.repo,
+          #         body: output
+          #       })
+          # - name: Comment on PR on error
+          #   uses: actions/github-script@v6
+          #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
+          #   with:
+          #     github-token: ${{ secrets.GITHUB_TOKEN }}
+          #     script: |
+          #       const output = `##### Plan:
+          #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+          #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+          #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+          #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+          #       github.rest.issues.createComment({
+          #         issue_number: context.issue.number,
+          #         owner: context.repo.owner,
+          #         repo: context.repo.repo,
+          #         body: output
+          #       })
+          # - name: Terraform Plan Status
+          #   if: steps.plan.outcome == 'failure'
+          #   run: exit 1 
