run

diff --git a/.github/workflows/terraform-pipeline-pr.yml b/.github/workflows/terraform-pipeline-pr.yml
--- a/.github/workflows/terraform-pipeline-pr.yml
+++ b/.github/workflows/terraform-pipeline-pr.yml
@@ -24,70 +24,87 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Configure AWS credentials for PR role
-        uses: aws-actions/configure-aws-credentials@v1.7.0
-        if: github.event_name == 'pull_request'
+      - name: Cache plugin dir
+        uses: actions/cache@v2
         with:
-          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PR_ROLE }}
-          role-session-name: github-demo
-          aws-region: ${{ env.AWS_REGION }}
-      - name: Terraform Init
-        id: init
-        run: terraform init
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -out plan
-        continue-on-error: true
-      - name: Terraform show plan output
-        uses: mathiasvr/command-output@v1
-        if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
-        id: plan_output
+          path: ~/.tflint.d/plugins
+          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}  
+      - name: Setup TFLint
+        uses: terraform-linters/setup-tflint@v2
         with:
-          run: terraform show -no-color plan
-      - name: Comment on PR on success
-        uses: actions/github-script@v6
-        if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
-        env:
-          PLAN: "${{ steps.plan_output.outputs.stdout }}"
-        with:
-          script: |
-            const output = `##### Plan:
-            ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`terraform\n
-            ${process.env.PLAN}
-            \n\`\`\`
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Comment on PR on error
-        uses: actions/github-script@v6
-        if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `##### Plan:
-            ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1 
+          tflint_version: v0.38.1
+      - name: Show version
+        run: tflint --version
+
+      - name: Init TFLint
+        run: tflint --init
+
+      - name: Run TFLint
+        run: tflint -f compact
+      # - name: Configure AWS credentials for PR role
+      #   uses: aws-actions/configure-aws-credentials@v1.7.0
+      #   if: github.event_name == 'pull_request'
+      #   with:
+      #     role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PR_ROLE }}
+      #     role-session-name: github-demo
+      #     aws-region: ${{ env.AWS_REGION }}
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -out plan
+      #   continue-on-error: true
+      # - name: Terraform show plan output
+      #   uses: mathiasvr/command-output@v1
+      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
+      #   id: plan_output
+      #   with:
+      #     run: terraform show -no-color plan
+      # - name: Comment on PR on success
+      #   uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'success'
+      #   env:
+      #     PLAN: "${{ steps.plan_output.outputs.stdout }}"
+      #   with:
+      #     script: |
+      #       const output = `##### Plan:
+      #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       <details><summary>Show Plan</summary>
+      #       \`\`\`terraform\n
+      #       ${process.env.PLAN}
+      #       \n\`\`\`
+      #       </details>
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+      # - name: Comment on PR on error
+      #   uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request' && steps.plan.outcome == 'failure'
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `##### Plan:
+      #       ###### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       ###### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       ###### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1 
